# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 15:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_cine_pelicula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='cines',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lupe', to='main.Cine'),
        ),
    ]
